### ISSUE TITLE
Assertion `args[1]->IsString()' failed.

### ISSUE THREAD

**Issue by hubtub2** [Bramichou/ThreeJS-Boilerplate#1]
Hi,

I tried your template and get the following error after yarn; yarn start

`> yarn
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.0.17: The platform "win32" is incompatible with this module.
info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excludi
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.21.1", whi
Done in 64.70s.`

`> yarn start
yarn run v1.19.1
$ gulp
[15:01:44] Requiring external module babel-register
gulp[28748]: c:\ws\src\node_contextify.cc:649: Assertion `args[1]->IsString()' failed.
 1: 00007FF6C151094F napi_wrap+124431
 2: 00007FF6C14B2696 v8::base::CPU::has_sse+34502
 3: 00007FF6C14B29B3 v8::base::CPU::has_sse+35299
 4: 00007FF6C14BCFC3 v8::base::CPU::has_sse+77811
 5: 00007FF6C1C6B150 v8::internal::Builtins::builtin_handle+325536
 6: 00007FF6C1C6A326 v8::internal::Builtins::builtin_handle+321910
 7: 00007FF6C1C6A9A2 v8::internal::Builtins::builtin_handle+323570
 8: 00007FF6C1C6A7DE v8::internal::Builtins::builtin_handle+323118
 9: 00007FF6C20E2D6D v8::internal::SetupIsolateDelegate::SetupHeap+568205
10: 00007FF6C205DF0A v8::internal::SetupIsolateDelegate::SetupHeap+23850
11: 00007FF6C2143A90 v8::internal::SetupIsolateDelegate::SetupHeap+964784
12: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
13: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
14: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
15: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
16: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
17: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
18: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
19: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
20: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
21: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
22: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
23: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
24: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
25: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
26: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
27: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
28: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
29: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
30: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
31: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
32: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
33: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
34: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
35: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
36: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
37: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
38: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
39: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
40: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
41: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
42: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
43: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
44: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
45: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
46: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
47: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
48: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
49: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
50: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
51: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
52: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
53: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
54: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
55: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
56: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
57: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
58: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
59: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
60: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
61: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
62: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
63: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
64: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
65: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
66: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
67: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
68: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
69: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
70: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
71: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
72: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
73: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
74: 00007FF6C205BBAC v8::internal::SetupIsolateDelegate::SetupHeap+14796
75: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
76: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
77: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
78: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
79: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
80: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
81: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
82: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
83: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
84: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
85: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
86: 00007FF6C20627FC v8::internal::SetupIsolateDelegate::SetupHeap+42524
87: 00007FF6C205BBAC v8::internal::SetupIsolateDelegate::SetupHeap+14796
88: 00007FF6C205FDB1 v8::internal::SetupIsolateDelegate::SetupHeap+31697
89: 00007FF6C205F99C v8::internal::SetupIsolateDelegate::SetupHeap+30652
90: 00007FF6C1BC4F43 v8::internal::Execution::CallWasm+1395
91: 00007FF6C1BC48C6 v8::internal::Execution::Call+182
92: 00007FF6C1C95B3B v8::Function::Call+603
93: 00007FF6C152CA45 node::CallbackScope::~CallbackScope+1429
94: 00007FF6C1525FE3 v8::internal::interpreter::BytecodeNode::operand_scale+179
95: 00007FF6C14AFBB3 v8::base::CPU::has_sse+23523
96: 00007FF6C14A4FE1 EVP_CIPHER_CTX_buf_noconst+200753
97: 00007FF6C155CFC7 uv_timer_stop+775
98: 00007FF6C1559AAB uv_async_send+331
99: 00007FF6C155924C uv_loop_init+1212
100: 00007FF6C1559414 uv_run+244
101: 00007FF6C147B892 EVP_CIPHER_CTX_buf_noconst+30946
102: 00007FF6C14D9263 node::Start+275
103: 00007FF6C139666C RC4_options+339308
104: 00007FF6C2195D58 v8::internal::SetupIsolateDelegate::SetupHeap+1301368
105: 00007FFCF8252784 BaseThreadInitThunk+20
106: 00007FFCF8C40C51 RtlUserThreadStart+33
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\data\src\webanno_threejs>`

**Comment by hubtub2** [comment]
Made it work using npm instead of yarn using fix from here: https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by Bramichou** [comment]
Hello @hubtub2, this boilerplate is not longer maintained, feel free to use another Three JS boilerplate, or make your own !
